#pragma once
#include <stdint.h>

struct CCLabel {
    uint8_t cc;
    const char* label;
};

// chase-bliss_mood-mkii_deluge
const CCLabel chase_bliss_mood_mkii_deluge[] = {
    { 0, nullptr },
    { 2, "CC2" },
    { 3, "Resonance" },
    { 4, "Cutoff" },
    { 5, "Wave" },
    { 6, "OSC2 Tune" },
    { 7, "Glide Amount" },
    { 8, "VC OS Level" },
    { 9, "Filter Tracking" },
    { 10, "Pan pot" },
    { 11, "Filter FM Amount" },
    { 12, "HP Cutoff" },
    { 13, "HP Resonance" },
    { 14, "Time" },
    { 15, "Mix" },
    { 16, "Length" },
    { 17, "Wet channel modify" },
    { 18, "Clock" },
    { 19, "Micro-looper modify" },
    { 20, "Ramp speed" },
    { 21, "Wet channel mode" },
    { 22, "Routing" },
    { 23, "Micro-looper mode" },
    { 24, "FX3 Parameter3" },
    { 25, "FX3 Parameter4" },
    { 26, "FX3 MIX" },
    { 27, "VCF EG Attack" },
    { 28, "VCF EG Decay" },
    { 29, "VCF EG Sustain" },
    { 30, "VCF EG Release" },
    { 31, "VCF EG Time" },
    { 32, "OSC1 Fine Pitch" },
    { 33, "VCF EG Level" },
    { 34, "VCA EG Attack" },
    { 35, "VCA EG Decay" },
    { 36, "VCA EG Sustain" },
    { 37, "VCA EG Release" },
    { 38, "VCA EG Time" },
    { 39, "OSC1 WF Shape" },
    { 40, "M1 Parameter1" },
    { 41, "M1 Parameter2" },
    { 42, "M1 Parameter3" },
    { 43, "M1 CV Level" },
    { 44, "M1 CV1 Level" },
    { 45, "M1 CV2 Level" },
    { 46, "M1 Wave Level" },
    { 47, "M1 Cutoff Level" },
    { 48, "M1 VCA Level" },
    { 49, "M1 FX1 Level" },
    { 50, "M1 FFM Level" },
    { 51, "MIDI clock ignore" },
    { 52, "Stop ramping" },
    { 53, "Wet channel clock division" },
    { 54, "Micro-looper channel clock division" },
    { 55, "True bypass mode" },
    { 56, "Factory reset" },
    { 57, "Octave transpose" },
    { 58, "M2 Parameter3" },
    { 59, "Exit synth mode" },
    { 60, "M2 CV1 Level" },
    { 61, "Time" },
    { 62, "Wet channel modify" },
    { 63, "Clock" },
    { 64, "Micro-looper channel modify" },
    { 65, "Length" },
    { 66, "Bounce" },
    { 67, "Sweep" },
    { 68, "Polarity" },
    { 69, "M2 FX3 Level" },
    { 70, "M2 Custom1 Level" },
    { 71, "Classic" },
    { 72, "Miso" },
    { 73, "Spread" },
    { 74, "Dry kill" },
    { 75, "Trails" },
    { 76, "Latch" },
    { 77, "Micro-looper no dub" },
    { 78, "Smooth" },
    { 79, "M3 Wave Level" },
    { 80, "Attack" },
    { 81, "Decay" },
    { 82, "Sustain" },
    { 83, "Release" },
    { 84, "Portamento" },
    { 85, "M3 FX3 Level" },
    { 86, "M3 Custom1 Level" },
    { 87, "Output type" },
    { 88, "M3 Custom3 Level" },
    { 89, "SEQ Length" },
    { 90, "SEQ Division" },
    { 91, "SEQ Probability" },
    { 92, "SEQ Swing" },
    { 93, "Tap tempo legacy" },
    { 94, "Chorus Speed" },
    { 95, "Chorus Feedback" },
    { 96, "Phaser DRY WET" },
    { 97, "Phaser Depth" },
    { 98, "Phaser Feedback" },
    { 99, "Flanger DRY WET" },
    { 100, "Expression over MIDI" },
    { 101, "Flanger Feedback" },
    { 102, "Micro-looper bypass" },
    { 103, "Wet channel bypass" },
    { 104, "Hidden menu" },
    { 105, "Wet channel freeze" },
    { 106, "Micro-looper freeze" },
    { 107, "Tap tempo" },
    { 108, "Free ENV1 Release" },
    { 109, "Free ENV1 Amount" },
    { 110, "MIDI reset" },
    { 111, "Preset save" },
    { 112, "Free ENV2 Decay" },
    { 113, "Free ENV2 Sustain" },
    { 114, "Free ENV2 Release" },
    { 115, "Free ENV2 Amount" },
    { 116, "Free ENV2 Velo Amount" },
    { 117, "AMP Delay" },
    { 118, "AMP Attack" },
    { 119, "AMP Decay" },
    { 0, nullptr }
};

// hydrasynth
const CCLabel hydrasynth[] = {
    { 0, nullptr },
    { 2, "Keyboard spice" },
    { 3, "Noise VOL" },
    { 4, "Expression Pedal" },
    { 5, "Glide Time" },
    { 6, "NRPN value MSB" },
    { 7, "Volume" },
    { 8, "Noise PAN" },
    { 9, "Ring MOD VOL" },
    { 10, "Ring MOD PAN" },
    { 11, "EXP Pedal" },
    { 12, "PRE Param1" },
    { 13, "PRE Param2" },
    { 14, "Delay Feedback" },
    { 15, "Delay Time" },
    { 16, "Macro1" },
    { 17, "Macro2" },
    { 18, "Macro3" },
    { 19, "Macro4" },
    { 20, "Macro5" },
    { 21, "Macro6" },
    { 22, "Macro7" },
    { 23, "Macro8" },
    { 24, "OSC1 Wavscan" },
    { 25, "ENV4 Attack" },
    { 26, "OSC2 WAV Scan" },
    { 27, "ENV4 Decay" },
    { 28, "LFO2 Gain" },
    { 29, "MUT1 Ratio" },
    { 30, "MUT1 Depth" },
    { 31, "MUT1 DRY WET" },
    { 32, "Grain PAN" },
    { 33, "MUT2 Ratio" },
    { 34, "MUT2 Depth" },
    { 35, "MUT2 DRY WET" },
    { 36, "MUT3 Ratio" },
    { 37, "MUT3 Depth" },
    { 38, "Pause Ramp Speed" },
    { 39, "MUT3 DRY WET" },
    { 40, "MUT4 Ratio" },
    { 41, "MUT4 Depth" },
    { 42, "MUT4 DRY WET" },
    { 43, "RM12 Depth" },
    { 44, "OSC1 VOL" },
    { 45, "OSC1 PAN" },
    { 46, "OSC2 VOL" },
    { 47, "OSC2 PAN" },
    { 48, "OSC3 VOL" },
    { 49, "OSC3 PAN" },
    { 50, "F1 Drive" },
    { 51, "F1 Keytrack" },
    { 52, "F1 Lfo1amt" },
    { 53, "F1 VEL ENV" },
    { 54, "F1 Env1amt" },
    { 55, "F2 Cutoff" },
    { 56, "F2 RES" },
    { 57, "F2 Type" },
    { 58, "F2 Keytrack" },
    { 59, "F2 Lfo1amt" },
    { 60, "F2 VEL ENV" },
    { 61, "F2 Env1amt" },
    { 62, "AMP Lfo2amt" },
    { 63, "Delay WET Tone" },
    { 64, "SUS Pedal" },
    { 65, "Reverb Time" },
    { 66, "Glide" },
    { 67, "Reverb Tone" },
    { 68, "Post Param1" },
    { 69, "Post Param2" },
    { 70, "LFO1 Gain" },
    { 71, "F1 RES" },
    { 72, "LFO1 Rate" },
    { 73, "LFO2 Rate" },
    { 74, "F1 Cutoff" },
    { 75, "LFO3 Gain" },
    { 76, "LFO3 Rate" },
    { 77, "LFO4 Gain" },
    { 78, "LFO4 Rate" },
    { 79, "LFO5 Gain" },
    { 80, "LFO5 Rate" },
    { 81, "ENV1 Attack" },
    { 82, "ENV1 Decay" },
    { 83, "ENV1 Sustain" },
    { 84, "ENV1 Release" },
    { 85, "ENV2 Attack" },
    { 86, "ENV2 Decay" },
    { 87, "ENV2 Sustain" },
    { 88, "ENV2 Release" },
    { 89, "ENV3 Attack" },
    { 90, "ENV3 Decay" },
    { 91, "Reverb DRY WET" },
    { 92, "Delay DRY WET" },
    { 93, "PRE MIX" },
    { 94, "Post MIX" },
    { 95, "Detune" },
    { 96, "ENV3 Sustain" },
    { 97, "ENV3 Release" },
    { 98, "Nrpn Param LSB" },
    { 99, "Nrpn Param MSB" },
    { 100, "Exppedal" },
    { 101, "RPN Param MSB" },
    { 102, "ENV5 Attack" },
    { 103, "ENV5 Decay" },
    { 104, "ENV5 Sustain" },
    { 105, "ENV5 Release" },
    { 106, "ARP Division" },
    { 107, "ARP Gate" },
    { 108, "ARP Mode" },
    { 109, "ARP Ratchet" },
    { 110, "ARP Chance" },
    { 111, "OSC1 Cent" },
    { 112, "OSC2 Cent" },
    { 113, "OSC3 Cent" },
    { 114, "OSC3 F Rate" },
    { 115, "Noise F Rate" },
    { 116, "Ring MOD F Rate" },
    { 117, "ST Width" },
    { 118, "OSC1 F Rate" },
    { 119, "OSC2 F Rate" },
    { 0, nullptr }
};

// lost_found
const CCLabel lost_found[] = {
    { 0, nullptr },
    { 2, "CC2" },
    { 3, "Resonance" },
    { 4, "Cutoff" },
    { 5, "Wave" },
    { 6, "OSC2 Tune" },
    { 7, "Glide Amount" },
    { 8, "VC OS Level" },
    { 9, "Filter Tracking" },
    { 10, "Pan pot" },
    { 11, "Filter FM Amount" },
    { 12, "HP Cutoff" },
    { 13, "HP Resonance" },
    { 14, "Left time" },
    { 15, "Mix" },
    { 16, "Right time" },
    { 17, "Left modify" },
    { 18, "Blend" },
    { 19, "Right modify" },
    { 20, "Ramp speed" },
    { 21, "Left effects mode" },
    { 22, "Routing" },
    { 23, "Right effects mode" },
    { 24, "Left alt" },
    { 25, "Spill" },
    { 26, "Right alt" },
    { 27, "Left EQ" },
    { 28, "Glue" },
    { 29, "Right EQ" },
    { 30, "Master wet volume" },
    { 31, "VCF EG Time" },
    { 32, "Spread" },
    { 33, "VCF EG Level" },
    { 34, "VCA EG Attack" },
    { 35, "VCA EG Decay" },
    { 36, "VCA EG Sustain" },
    { 37, "VCA EG Release" },
    { 38, "VCA EG Time" },
    { 39, "OSC1 WF Shape" },
    { 40, "M1 Parameter1" },
    { 41, "M1 Parameter2" },
    { 42, "M1 Parameter3" },
    { 43, "M1 CV Level" },
    { 44, "M1 CV1 Level" },
    { 45, "M1 CV2 Level" },
    { 46, "M1 Wave Level" },
    { 47, "M1 Cutoff Level" },
    { 48, "M1 VCA Level" },
    { 49, "M1 FX1 Level" },
    { 50, "M1 FFM Level" },
    { 51, "MIDI clock ignore" },
    { 52, "Ramping" },
    { 53, "Left tap subdivision" },
    { 54, "Right tap subdivision" },
    { 55, "True bypass mode" },
    { 56, "Factory reset" },
    { 57, "Dry kill" },
    { 58, "M2 Parameter3" },
    { 59, "Exit synth mode" },
    { 60, "M2 CV1 Level" },
    { 61, "Left time" },
    { 62, "Left modify" },
    { 63, "Blend" },
    { 64, "Right modify" },
    { 65, "Right time" },
    { 66, "Bounce" },
    { 67, "Sweep" },
    { 68, "Polarity" },
    { 69, "M2 FX3 Level" },
    { 70, "M2 Custom1 Level" },
    { 71, "Miso" },
    { 72, "Spread" },
    { 73, "Latch" },
    { 74, "Left swap" },
    { 75, "Right swap" },
    { 76, "Unsync" },
    { 77, "Trails" },
    { 78, "Bank" },
    { 79, "M3 Wave Level" },
    { 80, "Attack" },
    { 81, "Decay" },
    { 82, "Sustain" },
    { 83, "Release" },
    { 84, "Portamento" },
    { 85, "M3 FX3 Level" },
    { 86, "M3 Custom1 Level" },
    { 87, "Output type" },
    { 88, "M3 Custom3 Level" },
    { 89, "SEQ Length" },
    { 90, "SEQ Division" },
    { 91, "SEQ Probability" },
    { 92, "SEQ Swing" },
    { 93, "Tap tempo" },
    { 94, "Chorus Speed" },
    { 95, "Chorus Feedback" },
    { 96, "Phaser DRY WET" },
    { 97, "Phaser Depth" },
    { 98, "Phaser Feedback" },
    { 99, "Flanger DRY WET" },
    { 100, "Expression over MIDI" },
    { 101, "Flanger Feedback" },
    { 102, "Right footswitch" },
    { 103, "Left footswitch" },
    { 104, "Alt menu" },
    { 105, "Left hold" },
    { 106, "Right hold" },
    { 107, "Tap tempo" },
    { 108, "Free ENV1 Release" },
    { 109, "Free ENV1 Amount" },
    { 110, "MIDI reset" },
    { 111, "Save preset" },
    { 112, "Random left mode" },
    { 113, "Random right mode" },
    { 114, "Random both modes" },
    { 115, "Free ENV2 Amount" },
    { 116, "Free ENV2 Velo Amount" },
    { 117, "AMP Delay" },
    { 118, "AMP Attack" },
    { 119, "AMP Decay" },
    { 0, nullptr }
};

// microfreak
const CCLabel microfreak[] = {
    { 0, nullptr },
    { 2, "Keyboard spice" },
    { 3, "Density" },
    { 4, "Expression Pedal" },
    { 5, "Glide" },
    { 6, "NRPN value MSB" },
    { 7, "Volume" },
    { 8, "Cutoff" },
    { 9, "Type" },
    { 10, "Wave" },
    { 11, "Expression" },
    { 12, "Timbre" },
    { 13, "Shape" },
    { 14, "UNI CC14" },
    { 15, "UNI CC15" },
    { 16, "UNI CC16" },
    { 17, "BIP CC17" },
    { 18, "BIP CC18" },
    { 19, "BIP CC19" },
    { 20, "BIP CC20" },
    { 21, "BIP CC21" },
    { 22, "Direction" },
    { 23, "Cutoff" },
    { 24, "Cycling env amount" },
    { 25, "LFO Rate" },
    { 26, "Filter amount" },
    { 27, "Feedback Lowpass Filter" },
    { 28, "Cycling env hold" },
    { 29, "Envelope sustain" },
    { 30, "Head2 PAN" },
    { 31, "Head3 PAN" },
    { 32, "Grain PAN" },
    { 33, "Grain Stereo Spread" },
    { 34, "Head1 FB Switch" },
    { 35, "Head2 FB Switch" },
    { 36, "Head3 FB Switch" },
    { 37, "Head4 FB Switch" },
    { 38, "Pause Ramp Speed" },
    { 39, "Spring LVL" },
    { 40, "Spring Decay" },
    { 41, "SOS Mode" },
    { 42, "Pause NO Ramp" },
    { 43, "Pause Ramp" },
    { 44, "Reverse" },
    { 45, "INF Hold W OSC" },
    { 46, "INF Hold" },
    { 47, "SOS Repeat LVL" },
    { 48, "SOS Loop LVL" },
    { 49, "SOS REC Splice Clear" },
    { 50, "SOS Exit" },
    { 51, "Sync" },
    { 52, "Noise Level" },
    { 53, "LFO1 Shape" },
    { 54, nullptr },
    { 55, nullptr },
    { 56, nullptr },
    { 57, nullptr },
    { 58, "ARP ON OFF" },
    { 59, "ARP Mode" },
    { 60, "Midi EXP Switch" },
    { 61, "LFO2 Shape" },
    { 62, "LFO2 Rate" },
    { 63, "Midi CLK Switch" },
    { 64, "Keyboard hold button toggle" },
    { 65, "Glide Mode" },
    { 66, "Sostenuto" },
    { 67, "Soft" },
    { 68, "LFO3 Symmetry" },
    { 69, "Sostenuto 2" },
    { 70, "Algorithm" },
    { 71, "Resonance" },
    { 72, "Osc 3 mod 1 pitch" },
    { 73, "Attack" },
    { 74, "Filter Cutofff" },
    { 75, "Filter track" },
    { 76, "Osc 3 filter" },
    { 77, "Amp filter" },
    { 78, "Echo Switch" },
    { 79, "Decay Release" },
    { 80, "Freeze" },
    { 81, "FX1" },
    { 82, "FX2" },
    { 83, "Resonance" },
    { 84, "EQ frequency" },
    { 85, "EQ mix" },
    { 86, "Amp attack" },
    { 87, "Amp decay" },
    { 88, "Effect ON" },
    { 89, "TAP" },
    { 90, "Mod 1 attack" },
    { 91, "ARP SEQ rate free" },
    { 92, "ARP SEQ rate sync" },
    { 93, "LFO rate free" },
    { 94, "LFO rate sync" },
    { 95, "Mod 2 decay" },
    { 96, "Data Increment" },
    { 97, "Voices" },
    { 98, "Nrpn Param LSB" },
    { 99, "Nrpn Param MSB" },
    { 100, "Exppedal" },
    { 101, "RPN Param MSB" },
    { 102, "Cycling env rise" },
    { 103, "Cycling env fall" },
    { 104, "OP3 LVL" },
    { 105, "Envelope attack" },
    { 106, "Envelope decay" },
    { 107, "OP6 LVL" },
    { 108, "OP1 Ratio" },
    { 109, "OP2 Ratio" },
    { 110, "OP3 Ratio" },
    { 111, "OP4 Ratio" },
    { 112, "OP5 Ratio" },
    { 113, "OP6 Ratio" },
    { 114, "Animate 1 hold" },
    { 115, "Animate 2 hold" },
    { 116, "Arp clock gate" },
    { 117, "Pitch Quantization Mode" },
    { 118, "Freeze Mode" },
    { 119, "Expert Mode" },
    { 0, nullptr }
};

// micromonsta-2
const CCLabel micromonsta_2[] = {
    { 0, nullptr },
    { 2, "JOY Down" },
    { 3, "Mute" },
    { 4, "Foot Controller" },
    { 5, "Voice glide" },
    { 6, "Data Entry MSB" },
    { 7, "Volume" },
    { 8, "Audio In Level" },
    { 9, "Voice Mode" },
    { 10, "Unassigned" },
    { 11, "Reverb Level" },
    { 12, "DRY Level" },
    { 13, "MOD Speed" },
    { 14, "MOD Target" },
    { 15, "MOD Depth" },
    { 16, "Value Interpreter Mode" },
    { 17, "PRE Delay" },
    { 18, "Decay Length" },
    { 19, "Decay Texture" },
    { 20, "Mixing Structure" },
    { 21, "Filter cutoff 1" },
    { 22, "Filter cutoff 2 Filter width" },
    { 23, "Arpeggio speed" },
    { 24, "DCO2 and Env2 step amount" },
    { 25, "EQ" },
    { 26, "Delay time" },
    { 27, "Delay feedback" },
    { 28, "Delay level" },
    { 29, "Reverb decay" },
    { 30, "Reverb mod" },
    { 31, "Reverb level" },
    { 32, "Bank select LSB" },
    { 33, "Voice detune" },
    { 34, "Osc detune" },
    { 35, "Pan spread" },
    { 36, "VCA env velocity sensitivity" },
    { 37, "Filter env velocity sensitivity" },
    { 38, "Date Entry LSB" },
    { 39, "Osc 1 shape" },
    { 40, "Osc 1 tune" },
    { 41, "Osc 1 fine tune" },
    { 42, "Osc 2 shape" },
    { 43, "Osc 2 tune" },
    { 44, "Osc 2 fine tune" },
    { 45, "Osc 3 shape" },
    { 46, "Osc 3 tune" },
    { 47, "Osc 3 fine tune" },
    { 48, "Osc 1 level" },
    { 49, "Osc 2 level" },
    { 50, "Osc 3 level" },
    { 51, "Noise level" },
    { 52, "Mod matrix level 1" },
    { 53, "Mod matrix level 2" },
    { 54, "Mod matrix level 3" },
    { 55, "Mod matrix level 4" },
    { 56, "Mod matrix level 5" },
    { 57, "Mod matrix level 6" },
    { 58, "Mod matrix level 7" },
    { 59, "Mod matrix level 8" },
    { 60, "Mod matrix level 9" },
    { 61, "Mod matrix level 10" },
    { 62, "Lag level 1" },
    { 63, "AMP Porta" },
    { 64, "Sustain pedal" },
    { 65, "Glide switch" },
    { 66, "Osc 1 Octave" },
    { 67, "SEQ Length" },
    { 68, "Legato" },
    { 69, "SEQ Clear" },
    { 70, "Mod knob" },
    { 71, "Filter resonance" },
    { 72, "Env 1 release" },
    { 73, "Env 1 attack" },
    { 74, "Filter cutoff" },
    { 75, "Env 1 decay" },
    { 76, "LFO 1 speed" },
    { 77, "LFO 2 speed" },
    { 78, "LFO 3 speed" },
    { 79, "Env 1 sustain" },
    { 80, "Env 2 attack" },
    { 81, "Env 2 decay" },
    { 82, "Env 2 sustain" },
    { 83, "Env 2 release" },
    { 84, "Env 3 attack" },
    { 85, "Env 3 decay" },
    { 86, "Env 3 sustain" },
    { 87, "Env 3 release" },
    { 88, "Filter envelope" },
    { 89, "Filter tracking" },
    { 90, "Filter FM" },
    { 91, "Voice drive" },
    { 92, "LFO1 Multiply" },
    { 93, "LFO1 Speed" },
    { 94, "LFO1 Interlace" },
    { 95, "LFO1 Depth" },
    { 96, "Date Inc" },
    { 97, "Data Dec" },
    { 98, "NRPN Param LSB" },
    { 99, "NRPN Param MSB" },
    { 100, "MOD Slot1 Source" },
    { 101, "MOD Slot2 Source" },
    { 102, "DCO2 Waveform" },
    { 103, "DCO2 PW" },
    { 104, "DCO2 offset" },
    { 105, "DCO2 amplitude" },
    { 106, "DCO2 octave" },
    { 107, "DCO2 frequency" },
    { 108, "Env1 Attack" },
    { 109, "Env1 Attack Level" },
    { 110, "Env1 Decay" },
    { 111, "Env1 Sustain Level" },
    { 112, "Env1 Release" },
    { 113, "Env1 Offset" },
    { 114, "Env2 Attack" },
    { 115, "Env2 Attack Level" },
    { 116, "Env2 Decay" },
    { 117, "Env2 Sustain Level" },
    { 118, "Env2 Release" },
    { 119, "Env2 Offset" },
    { 0, nullptr }
};

// mood_mk2
const CCLabel mood_mk2[] = {
    { 0, nullptr },
    { 2, "Keyboard spice" },
    { 3, "Polyphony Mode" },
    { 4, "Expression Pedal" },
    { 5, "Portamento Rate" },
    { 6, "NRPN value MSB" },
    { 7, "Volume" },
    { 8, "Noise PAN" },
    { 9, "Pre-Glide" },
    { 10, "Ring MOD PAN" },
    { 11, "Expression" },
    { 12, "PRE Param1" },
    { 13, "Keyboard Octave" },
    { 14, "Delay Feedback" },
    { 15, "Delay Time" },
    { 16, "Macro1" },
    { 17, "Macro2" },
    { 18, "Macro3" },
    { 19, "osc 1 wave" },
    { 20, "osc 1 wave interpolate" },
    { 21, "osc 1 pulse width index" },
    { 22, "osc 1 virtual sync depth" },
    { 23, "Macro8" },
    { 24, "osc 1 density" },
    { 25, "osc 1 density detune" },
    { 26, "osc 1 semitones" },
    { 27, "osc 1 cents" },
    { 28, "osc 1 pitchbend" },
    { 29, "osc 2 wave" },
    { 30, "osc 2 wave interpolate" },
    { 31, "osc 2 pulse width index" },
    { 32, "Grain PAN" },
    { 33, "osc 2 virtual sync depth" },
    { 34, "MUT2 Depth" },
    { 35, "osc 2 density" },
    { 36, "osc 2 density detune" },
    { 37, "osc 2 semitones" },
    { 38, "Pause Ramp Speed" },
    { 39, "osc 2 cents" },
    { 40, "osc 2 pitchbend" },
    { 41, "Octave" },
    { 42, "Detune" },
    { 43, "VCO EG depth" },
    { 44, "Cutoff" },
    { 45, "VCF EG intensity" },
    { 46, "Rate" },
    { 47, "Pitch intensity" },
    { 48, "Cutoff intensity" },
    { 49, "Attack" },
    { 50, "Decay release" },
    { 51, "osc 1 level" },
    { 52, "osc 2 level" },
    { 53, "Delay feedback" },
    { 54, "ring mod level" },
    { 55, "F2 Cutoff" },
    { 56, "noise level" },
    { 57, "F2 Type" },
    { 58, "pre FX level" },
    { 59, "post FX level" },
    { 60, "routing" },
    { 61, "F2 Env1amt" },
    { 62, "AMP Lfo2amt" },
    { 63, "drive" },
    { 64, "SUS Pedal" },
    { 65, "drive type" },
    { 66, "Glide" },
    { 67, "Reverb Tone" },
    { 68, "type" },
    { 69, "tracking" },
    { 70, "env 1 sustain" },
    { 71, "resonance" },
    { 72, "env 1 release" },
    { 73, "env 1 attack" },
    { 74, "frequency" },
    { 75, "env 1 decay" },
    { 76, "LFO3 Rate" },
    { 77, "LFO4 Gain" },
    { 78, "Q normalise" },
    { 79, "env 2 to frequency" },
    { 80, "macro knob 1 position" },
    { 81, "macro knob 2 position" },
    { 82, "macro knob 3 position" },
    { 83, "macro knob 4 position" },
    { 84, "macro knob 5 position" },
    { 85, "macro knob 6 position" },
    { 86, "macro knob 7 position" },
    { 87, "macro knob 8 position" },
    { 88, "ENV2 Release" },
    { 89, "ENV3 Attack" },
    { 90, "ENV3 Decay" },
    { 91, "distortion level" },
    { 92, "Delay DRY WET" },
    { 93, "chorus level" },
    { 94, "Post MIX" },
    { 95, "Detune" },
    { 96, "ENV3 Sustain" },
    { 97, "ENV3 Release" },
    { 98, "Nrpn Param LSB" },
    { 99, "Nrpn Param MSB" },
    { 100, "Exppedal" },
    { 101, "RPN Param MSB" },
    { 102, "ENV5 Attack" },
    { 103, "ENV5 Decay" },
    { 104, "ENV5 Sustain" },
    { 105, "ENV5 Release" },
    { 106, "ARP Division" },
    { 107, "ARP Gate" },
    { 108, "env 1 velocity" },
    { 109, "ARP Ratchet" },
    { 110, "ARP Chance" },
    { 111, "OSC1 Cent" },
    { 112, "OSC2 Cent" },
    { 113, "OSC3 Cent" },
    { 114, "OSC3 F Rate" },
    { 115, "Noise F Rate" },
    { 116, "Ring MOD F Rate" },
    { 117, "ST Width" },
    { 118, "OSC1 F Rate" },
    { 119, "OSC2 F Rate" },
    { 0, nullptr }
};

// neutron
const CCLabel neutron[] = {
    { 0, nullptr },
    { 2, "JOY Down" },
    { 3, "Mute" },
    { 4, "Foot Controller" },
    { 5, "Voice glide" },
    { 6, "Data Entry MSB" },
    { 7, "Volume" },
    { 8, "Audio In Level" },
    { 9, "Voice Mode" },
    { 10, "Unassigned" },
    { 11, "Reverb Level" },
    { 12, "DRY Level" },
    { 13, "MOD Speed" },
    { 14, "MOD Target" },
    { 15, "MOD Depth" },
    { 16, "Value Interpreter Mode" },
    { 17, "PRE Delay" },
    { 18, "Decay Length" },
    { 19, "Decay Texture" },
    { 20, "Mixing Structure" },
    { 21, "Filter cutoff 1" },
    { 22, "Filter cutoff 2 Filter width" },
    { 23, "Arpeggio speed" },
    { 24, "DCO2 and Env2 step amount" },
    { 25, "EQ" },
    { 26, "Delay time" },
    { 27, "Delay feedback" },
    { 28, "Delay level" },
    { 29, "Reverb decay" },
    { 30, "Reverb mod" },
    { 31, "Reverb level" },
    { 32, "Bank select LSB" },
    { 33, "Voice detune" },
    { 34, "Osc detune" },
    { 35, "Pan spread" },
    { 36, "VCA env velocity sensitivity" },
    { 37, "Filter env velocity sensitivity" },
    { 38, "Date Entry LSB" },
    { 39, "Osc 1 shape" },
    { 40, "Damper pedal on off" },
    { 41, "Osc 1 fine tune" },
    { 42, "Osc 2 shape" },
    { 43, "Osc 2 tune" },
    { 44, "Osc 2 fine tune" },
    { 45, "Osc 3 shape" },
    { 46, "Osc 3 tune" },
    { 47, "Osc 3 fine tune" },
    { 48, "Osc 1 level" },
    { 49, "Osc 2 level" },
    { 50, "Osc 3 level" },
    { 51, "Noise level" },
    { 52, "Mod matrix level 1" },
    { 53, "Mod matrix level 2" },
    { 54, "Mod matrix level 3" },
    { 55, "Mod matrix level 4" },
    { 56, "Mod matrix level 5" },
    { 57, "Mod matrix level 6" },
    { 58, "Mod matrix level 7" },
    { 59, "Mod matrix level 8" },
    { 60, "Mod matrix level 9" },
    { 61, "Mod matrix level 10" },
    { 62, "Lag level 1" },
    { 63, "AMP Porta" },
    { 64, "Sustain pedal" },
    { 65, "Glide switch" },
    { 66, "Osc 1 Octave" },
    { 67, "SEQ Length" },
    { 68, "Legato" },
    { 69, "SEQ Clear" },
    { 70, "Mod knob" },
    { 71, "Filter resonance" },
    { 72, "Env 1 release" },
    { 73, "Env 1 attack" },
    { 74, "Filter cutoff" },
    { 75, "Env 1 decay" },
    { 76, "LFO 1 speed" },
    { 77, "LFO 2 speed" },
    { 78, "LFO 3 speed" },
    { 79, "Env 1 sustain" },
    { 80, "Env 2 attack" },
    { 81, "Env 2 decay" },
    { 82, "Env 2 sustain" },
    { 83, "Env 2 release" },
    { 84, "Env 3 attack" },
    { 85, "Env 3 decay" },
    { 86, "Env 3 sustain" },
    { 87, "Env 3 release" },
    { 88, "Filter envelope" },
    { 89, "Filter tracking" },
    { 90, "Filter FM" },
    { 91, "Voice drive" },
    { 92, "LFO1 Multiply" },
    { 93, "LFO1 Speed" },
    { 94, "LFO1 Interlace" },
    { 95, "LFO1 Depth" },
    { 96, "Date Inc" },
    { 97, "Data Dec" },
    { 98, "NRPN Param LSB" },
    { 99, "NRPN Param MSB" },
    { 100, "MOD Slot1 Source" },
    { 101, "MOD Slot2 Source" },
    { 102, "DCO2 Waveform" },
    { 103, "DCO2 PW" },
    { 104, "DCO2 offset" },
    { 105, "DCO2 amplitude" },
    { 106, "DCO2 octave" },
    { 107, "DCO2 frequency" },
    { 108, "Env1 Attack" },
    { 109, "Env1 Attack Level" },
    { 110, "Env1 Decay" },
    { 111, "Env1 Sustain Level" },
    { 112, "Env1 Release" },
    { 113, "Env1 Offset" },
    { 114, "Env2 Attack" },
    { 115, "Env2 Attack Level" },
    { 116, "Env2 Decay" },
    { 117, "Env2 Sustain Level" },
    { 118, "Env2 Release" },
    { 119, "Env2 Offset" },
    { 0, nullptr }
};

// polyend_acd
const CCLabel polyend_acd[] = {
    { 20, "Osc Saw Mix" },
    { 21, "Osc Square Mix" },
    { 22, "Osc Sub Mix" },
    { 23, "Osc Noise" },
    { 24, "Osc Pulse Width" },
    { 25, "PW LFO" },
    { 26, "PW Env" },
    { 27, "Pitch LFO" },
    { 54, "LFO Frequency" },
    { 71, "Filter Resonance" },
    { 72, "Amp Env Decay" },
    { 73, "Amp Env Release" },
    { 74, "Filter Cutoff" },
    { 75, "Amp Env Attack" },
    { 76, "Amp Env Sustain" },
    { 77, "Filter Env Amount" },
    { 78, "Filter LFO" },
    { 80, "Filter Env Attack" },
    { 81, "Filter Env Decay" },
    { 82, "Filter Env Sustain" },
    { 83, "Filter Env Release" },
    { 0, nullptr }
};

// polyend_fat
const CCLabel polyend_fat[] = {
    { 20, "Osc Timbre" },
    { 21, "Osc Noise" },
    { 22, "Osc Fatness" },
    { 23, "Osc Brightness" },
    { 24, "Fatness LFO" },
    { 54, "LFO Frequency" },
    { 71, "Filter Resonance" },
    { 72, "Amp Env Decay" },
    { 73, "Amp Env Release" },
    { 74, "Filter Cutoff" },
    { 75, "Amp Env Attack" },
    { 76, "Amp Env Sustain" },
    { 77, "Filter Env Amount" },
    { 78, "Filter LFO" },
    { 80, "Filter Env Attack" },
    { 81, "Filter Env Decay" },
    { 82, "Filter Env Sustain" },
    { 83, "Filter Env Release" },
    { 0, nullptr }
};

// polyend_grain
const CCLabel polyend_grain[] = {
    { 20, "Grain Position" },
    { 21, "Pos Spread" },
    { 22, "Time Spread" },
    { 23, "Density" },
    { 24, "Grain Size" },
    { 25, "Grain Shape" },
    { 26, "Detune Spread" },
    { 27, "Pan Spread" },
    { 30, "Osc Tune" },
    { 31, "Osc Finetune" },
    { 85, "Grain Space" },
    { 86, "Direction" },
    { 87, "Size Spread" },
    { 71, "Filter Resonance" },
    { 74, "Filter Cutoff" },
    { 77, "Filter Env Amount" },
    { 72, "Amp Env Decay" },
    { 73, "Amp Env Release" },
    { 75, "Amp Env Attack" },
    { 76, "Amp Env Sustain" },
    { 80, "Filter Env Attack" },
    { 81, "Filter Env Decay" },
    { 82, "Filter Env Sustain" },
    { 83, "Filter Env Release" },
    { 46, "Aux Env Attack" },
    { 47, "Aux Env Decay" },
    { 48, "Aux Env Sustain" },
    { 49, "Aux Env Release" },
    { 0, nullptr }
};

// polyend_phz
const CCLabel polyend_phz[] = {
    { 20, "Osc Mix" },
    { 21, "Osc1 Xmod" },
    { 22, "Osc Shape 1" },
    { 23, "Osc1 Ymod" },
    { 24, "Osc Detune" },
    { 25, "Osc Tune 1" },
    { 26, "Osc Finetune" },
    { 27, "Osc Shape 2" },
    { 28, "Osc2 Xmod" },
    { 29, "Osc2 Ymod" },
    { 30, "Osc Tune 2" },
    { 46, "Aux Env Attack" },
    { 47, "Aux Env Decay" },
    { 48, "Aux Env Sustain" },
    { 49, "Aux Env Release" },
    { 71, "Filter Resonance" },
    { 74, "Filter Cutoff" },
    { 77, "Filter Env Amount" },
    { 72, "Amp Env Decay" },
    { 73, "Amp Env Release" },
    { 75, "Amp Env Attack" },
    { 76, "Amp Env Sustain" },
    { 80, "Filter Env Attack" },
    { 81, "Filter Env Decay" },
    { 82, "Filter Env Sustain" },
    { 83, "Filter Env Release" },
    { 0, nullptr }
};

// polyend_pmd
const CCLabel polyend_pmd[] = {
    { 20, "Bow Level" },
    { 21, "Bow Timbre" },
    { 22, "Air Level" },
    { 23, "Air Flow" },
    { 24, "Air Timbre" },
    { 25, "Strike Level" },
    { 26, "Strike Mallet" },
    { 27, "Strike Timbre" },
    { 70, "Res Form" },
    { 71, "Res Damping" },
    { 74, "Res Brightness" },
    { 85, "Res Position" },
    { 86, "Res Space" },
    { 72, "Exc Env Decay" },
    { 73, "Exc Env Release" },
    { 75, "Exc Env Attack" },
    { 76, "Exc Env Sustain" },
    { 46, "Aux Env Attack" },
    { 47, "Aux Env Decay" },
    { 48, "Aux Env Sustain" },
    { 49, "Aux Env Release" },
    { 0, nullptr }
};

// polyend_vap
const CCLabel polyend_vap[] = {
    { 20, "Osc Mix" },
    { 21, "Osc PW 1" },
    { 22, "Osc Shape 1" },
    { 23, "Osc Noise" },
    { 25, "Osc Tune 1" },
    { 26, "Osc Detune" },
    { 27, "Osc Shape 2" },
    { 28, "Osc PW 2" },
    { 30, "Osc Tune 2" },
    { 31, "Osc Finetune" },
    { 46, "Aux Env Attack" },
    { 47, "Aux Env Decay" },
    { 48, "Aux Env Sustain" },
    { 49, "Aux Env Release" },
    { 71, "Filter Resonance" },
    { 74, "Filter Cutoff" },
    { 77, "Filter Env Amount" },
    { 72, "Amp Env Decay" },
    { 73, "Amp Env Release" },
    { 75, "Amp Env Attack" },
    { 76, "Amp Env Sustain" },
    { 80, "Filter Env Attack" },
    { 81, "Filter Env Decay" },
    { 82, "Filter Env Sustain" },
    { 83, "Filter Env Release" },
    { 0, nullptr }
};

// polyend_wavs
const CCLabel polyend_wavs[] = {
    { 20, "Osc Mix" },
    { 21, "Osc Warp 1" },
    { 22, "Osc Position 1" },
    { 25, "Osc Tune 1" },
    { 26, "Osc Finetune" },
    { 27, "Osc Position 2" },
    { 28, "Osc Warp 2" },
    { 29, "Osc Noise" },
    { 30, "Osc Tune 2" },
    { 31, "Osc Detune" },
    { 46, "Aux Env Attack" },
    { 47, "Aux Env Decay" },
    { 48, "Aux Env Sustain" },
    { 49, "Aux Env Release" },
    { 71, "Filter Resonance" },
    { 74, "Filter Cutoff" },
    { 77, "Filter Env Amount" },
    { 72, "Amp Env Decay" },
    { 73, "Amp Env Release" },
    { 75, "Amp Env Attack" },
    { 76, "Amp Env Sustain" },
    { 80, "Filter Env Attack" },
    { 81, "Filter Env Decay" },
    { 82, "Filter Env Sustain" },
    { 83, "Filter Env Release" },
    { 0, nullptr }
};

// polyend_wtfm
const CCLabel polyend_wtfm[] = {
    { 20, "FM Amount" },
    { 21, "Feedback 1" },
    { 22, "Osc Shape 1" },
    { 23, "Ratio 1" },
    { 24, "Ratio 2" },
    { 25, "Finetune 2" },
    { 26, "Finetune 1" },
    { 27, "Osc Shape 2" },
    { 28, "Feedback 2" },
    { 29, "FB 2->1" },
    { 46, "Aux Env Attack" },
    { 47, "Aux Env Decay" },
    { 48, "Aux Env Sustain" },
    { 49, "Aux Env Release" },
    { 71, "Filter Resonance" },
    { 74, "Filter Cutoff" },
    { 77, "Filter Env Amount" },
    { 72, "Amp Env Decay" },
    { 73, "Amp Env Release" },
    { 75, "Amp Env Attack" },
    { 76, "Amp Env Sustain" },
    { 80, "Filter Env Attack" },
    { 81, "Filter Env Decay" },
    { 82, "Filter Env Sustain" },
    { 83, "Filter Env Release" },
    { 0, nullptr }
};

// volca-beats
const CCLabel volca_beats[] = {
    { 0, nullptr },
    { 2, "JOY Down" },
    { 3, "Mute" },
    { 4, "Foot Controller" },
    { 5, "Voice glide" },
    { 6, "Data Entry MSB" },
    { 7, "Volume" },
    { 8, "Audio In Level" },
    { 9, "Voice Mode" },
    { 10, "Unassigned" },
    { 11, "Reverb Level" },
    { 12, "DRY Level" },
    { 13, "MOD Speed" },
    { 14, "MOD Target" },
    { 15, "MOD Depth" },
    { 16, "Value Interpreter Mode" },
    { 17, "PRE Delay" },
    { 18, "Decay Length" },
    { 19, "Decay Texture" },
    { 20, "Mixing Structure" },
    { 21, "Filter cutoff 1" },
    { 22, "Filter cutoff 2 Filter width" },
    { 23, "Arpeggio speed" },
    { 24, "DCO2 and Env2 step amount" },
    { 25, "EQ" },
    { 26, "Delay time" },
    { 27, "Delay feedback" },
    { 28, "Delay level" },
    { 29, "Reverb decay" },
    { 30, "Reverb mod" },
    { 31, "Reverb level" },
    { 32, "Bank select LSB" },
    { 33, "Voice detune" },
    { 34, "Osc detune" },
    { 35, "Pan spread" },
    { 36, "VCA env velocity sensitivity" },
    { 37, "Filter env velocity sensitivity" },
    { 38, "Date Entry LSB" },
    { 39, "Osc 1 shape" },
    { 40, "Kick level" },
    { 41, "Snare level" },
    { 42, "Lo tom level" },
    { 43, "Hi tom level" },
    { 44, "Closed hat level" },
    { 45, "Open hat level" },
    { 46, "Clap level" },
    { 47, "Claves level" },
    { 48, "Agogo level" },
    { 49, "Crash level" },
    { 50, "Clap PCM speed" },
    { 51, "Claves PCM speed" },
    { 52, "Agogo PCM speed" },
    { 53, "Crash PCM speed" },
    { 54, "Stutter time" },
    { 55, "Stutter depth" },
    { 56, "Tom decay" },
    { 57, "Closed hat decay" },
    { 58, "Open hat decay" },
    { 59, "Hat grain" },
    { 60, "Mod matrix level 9" },
    { 61, "Mod matrix level 10" },
    { 62, "Lag level 1" },
    { 63, "AMP Porta" },
    { 64, "Sustain pedal" },
    { 65, "Glide switch" },
    { 66, "Osc 1 Octave" },
    { 67, "SEQ Length" },
    { 68, "Legato" },
    { 69, "SEQ Clear" },
    { 70, "Mod knob" },
    { 71, "Filter resonance" },
    { 72, "Env 1 release" },
    { 73, "Env 1 attack" },
    { 74, "Filter cutoff" },
    { 75, "Env 1 decay" },
    { 76, "LFO 1 speed" },
    { 77, "LFO 2 speed" },
    { 78, "LFO 3 speed" },
    { 79, "Env 1 sustain" },
    { 80, "Env 2 attack" },
    { 81, "Env 2 decay" },
    { 82, "Env 2 sustain" },
    { 83, "Env 2 release" },
    { 84, "Env 3 attack" },
    { 85, "Env 3 decay" },
    { 86, "Env 3 sustain" },
    { 87, "Env 3 release" },
    { 88, "Filter envelope" },
    { 89, "Filter tracking" },
    { 90, "Filter FM" },
    { 91, "Voice drive" },
    { 92, "LFO1 Multiply" },
    { 93, "LFO1 Speed" },
    { 94, "LFO1 Interlace" },
    { 95, "LFO1 Depth" },
    { 96, "Date Inc" },
    { 97, "Data Dec" },
    { 98, "NRPN Param LSB" },
    { 99, "NRPN Param MSB" },
    { 100, "MOD Slot1 Source" },
    { 101, "MOD Slot2 Source" },
    { 102, "DCO2 Waveform" },
    { 103, "DCO2 PW" },
    { 104, "DCO2 offset" },
    { 105, "DCO2 amplitude" },
    { 106, "DCO2 octave" },
    { 107, "DCO2 frequency" },
    { 108, "Env1 Attack" },
    { 109, "Env1 Attack Level" },
    { 110, "Env1 Decay" },
    { 111, "Env1 Sustain Level" },
    { 112, "Env1 Release" },
    { 113, "Env1 Offset" },
    { 114, "Env2 Attack" },
    { 115, "Env2 Attack Level" },
    { 116, "Env2 Decay" },
    { 117, "Env2 Sustain Level" },
    { 118, "Env2 Release" },
    { 119, "Env2 Offset" },
    { 0, nullptr }
};

// volca-fm
const CCLabel volca_fm[] = {
    { 0, nullptr },
    { 2, "Keyboard spice" },
    { 3, "Noise VOL" },
    { 4, "Expression Pedal" },
    { 5, "Glide Time" },
    { 6, "NRPN value MSB" },
    { 7, "Volume" },
    { 8, "Noise PAN" },
    { 9, "Ring MOD VOL" },
    { 10, "Ring MOD PAN" },
    { 11, "EXP Pedal" },
    { 12, "PRE Param1" },
    { 13, "PRE Param2" },
    { 14, "Delay Feedback" },
    { 15, "Delay Time" },
    { 16, "Macro1" },
    { 17, "Macro2" },
    { 18, "Macro3" },
    { 19, "Macro4" },
    { 20, "Macro5" },
    { 21, "Macro6" },
    { 22, "Macro7" },
    { 23, "Macro8" },
    { 24, "OSC1 Wavscan" },
    { 25, "ENV4 Attack" },
    { 26, "OSC2 WAV Scan" },
    { 27, "ENV4 Decay" },
    { 28, "LFO2 Gain" },
    { 29, "MUT1 Ratio" },
    { 30, "MUT1 Depth" },
    { 31, "MUT1 DRY WET" },
    { 32, "Grain PAN" },
    { 33, "MUT2 Ratio" },
    { 34, "MUT2 Depth" },
    { 35, "MUT2 DRY WET" },
    { 36, "MUT3 Ratio" },
    { 37, "MUT3 Depth" },
    { 38, "Pause Ramp Speed" },
    { 39, "MUT3 DRY WET" },
    { 40, "Transpose" },
    { 41, "Velocity" },
    { 42, "Modulator attack" },
    { 43, "Modulator decay" },
    { 44, "Carrier attack" },
    { 45, "Carrier decay" },
    { 46, "LFO rate" },
    { 47, "LFO pitch depth" },
    { 48, "Arpeggiator type" },
    { 49, "OSC3 PAN" },
    { 50, "Arpeggiator div" },
    { 51, "F1 Keytrack" },
    { 52, "F1 Lfo1amt" },
    { 53, "F1 VEL ENV" },
    { 54, "F1 Env1amt" },
    { 55, "F2 Cutoff" },
    { 56, "F2 RES" },
    { 57, "F2 Type" },
    { 58, "F2 Keytrack" },
    { 59, "F2 Lfo1amt" },
    { 60, "F2 VEL ENV" },
    { 61, "F2 Env1amt" },
    { 62, "AMP Lfo2amt" },
    { 63, "Delay WET Tone" },
    { 64, "SUS Pedal" },
    { 65, "Reverb Time" },
    { 66, "Glide" },
    { 67, "Reverb Tone" },
    { 68, "Post Param1" },
    { 69, "Post Param2" },
    { 70, "LFO1 Gain" },
    { 71, "F1 RES" },
    { 72, "LFO1 Rate" },
    { 73, "LFO2 Rate" },
    { 74, "F1 Cutoff" },
    { 75, "LFO3 Gain" },
    { 76, "LFO3 Rate" },
    { 77, "LFO4 Gain" },
    { 78, "LFO4 Rate" },
    { 79, "LFO5 Gain" },
    { 80, "LFO5 Rate" },
    { 81, "ENV1 Attack" },
    { 82, "ENV1 Decay" },
    { 83, "ENV1 Sustain" },
    { 84, "ENV1 Release" },
    { 85, "ENV2 Attack" },
    { 86, "ENV2 Decay" },
    { 87, "ENV2 Sustain" },
    { 88, "ENV2 Release" },
    { 89, "ENV3 Attack" },
    { 90, "ENV3 Decay" },
    { 91, "Reverb DRY WET" },
    { 92, "Delay DRY WET" },
    { 93, "PRE MIX" },
    { 94, "Post MIX" },
    { 95, "Detune" },
    { 96, "ENV3 Sustain" },
    { 97, "ENV3 Release" },
    { 98, "Nrpn Param LSB" },
    { 99, "Nrpn Param MSB" },
    { 100, "Exppedal" },
    { 101, "RPN Param MSB" },
    { 102, "ENV5 Attack" },
    { 103, "ENV5 Decay" },
    { 104, "ENV5 Sustain" },
    { 105, "ENV5 Release" },
    { 106, "ARP Division" },
    { 107, "ARP Gate" },
    { 108, "ARP Mode" },
    { 109, "ARP Ratchet" },
    { 110, "ARP Chance" },
    { 111, "OSC1 Cent" },
    { 112, "OSC2 Cent" },
    { 113, "OSC3 Cent" },
    { 114, "OSC3 F Rate" },
    { 115, "Noise F Rate" },
    { 116, "Ring MOD F Rate" },
    { 117, "ST Width" },
    { 118, "OSC1 F Rate" },
    { 119, "OSC2 F Rate" },
    { 0, nullptr }
};

// volca-keys
const CCLabel volca_keys[] = {
    { 0, nullptr },
    { 2, "Keyboard spice" },
    { 3, "Noise VOL" },
    { 4, "Expression Pedal" },
    { 5, "Portamento" },
    { 6, "NRPN value MSB" },
    { 7, "Volume" },
    { 8, "Noise PAN" },
    { 9, "Ring MOD VOL" },
    { 10, "Ring MOD PAN" },
    { 11, "Expression" },
    { 12, "PRE Param1" },
    { 13, "PRE Param2" },
    { 14, "Delay Feedback" },
    { 15, "Delay Time" },
    { 16, "Macro1" },
    { 17, "Macro2" },
    { 18, "Macro3" },
    { 19, "Macro4" },
    { 20, "Macro5" },
    { 21, "Macro6" },
    { 22, "Macro7" },
    { 23, "Macro8" },
    { 24, "OSC1 Wavscan" },
    { 25, "ENV4 Attack" },
    { 26, "OSC2 WAV Scan" },
    { 27, "ENV4 Decay" },
    { 28, "LFO2 Gain" },
    { 29, "MUT1 Ratio" },
    { 30, "MUT1 Depth" },
    { 31, "MUT1 DRY WET" },
    { 32, "Grain PAN" },
    { 33, "MUT2 Ratio" },
    { 34, "MUT2 Depth" },
    { 35, "MUT2 DRY WET" },
    { 36, "MUT3 Ratio" },
    { 37, "MUT3 Depth" },
    { 38, "Pause Ramp Speed" },
    { 39, "MUT3 DRY WET" },
    { 40, "Voice" },
    { 41, "Octave" },
    { 42, "Detune" },
    { 43, "VCO EG depth" },
    { 44, "Cutoff" },
    { 45, "VCF EG intensity" },
    { 46, "Rate" },
    { 47, "Pitch intensity" },
    { 48, "Cutoff intensity" },
    { 49, "Attack" },
    { 50, "Decay release" },
    { 51, "Sustain" },
    { 52, "Delay time" },
    { 53, "Delay feedback" },
    { 54, "F1 Env1amt" },
    { 55, "F2 Cutoff" },
    { 56, "F2 RES" },
    { 57, "F2 Type" },
    { 58, "F2 Keytrack" },
    { 59, "F2 Lfo1amt" },
    { 60, "F2 VEL ENV" },
    { 61, "F2 Env1amt" },
    { 62, "AMP Lfo2amt" },
    { 63, "Delay WET Tone" },
    { 64, "SUS Pedal" },
    { 65, "Reverb Time" },
    { 66, "Glide" },
    { 67, "Reverb Tone" },
    { 68, "Post Param1" },
    { 69, "Post Param2" },
    { 70, "LFO1 Gain" },
    { 71, "F1 RES" },
    { 72, "LFO1 Rate" },
    { 73, "LFO2 Rate" },
    { 74, "F1 Cutoff" },
    { 75, "LFO3 Gain" },
    { 76, "LFO3 Rate" },
    { 77, "LFO4 Gain" },
    { 78, "LFO4 Rate" },
    { 79, "LFO5 Gain" },
    { 80, "LFO5 Rate" },
    { 81, "ENV1 Attack" },
    { 82, "ENV1 Decay" },
    { 83, "ENV1 Sustain" },
    { 84, "ENV1 Release" },
    { 85, "ENV2 Attack" },
    { 86, "ENV2 Decay" },
    { 87, "ENV2 Sustain" },
    { 88, "ENV2 Release" },
    { 89, "ENV3 Attack" },
    { 90, "ENV3 Decay" },
    { 91, "Reverb DRY WET" },
    { 92, "Delay DRY WET" },
    { 93, "PRE MIX" },
    { 94, "Post MIX" },
    { 95, "Detune" },
    { 96, "ENV3 Sustain" },
    { 97, "ENV3 Release" },
    { 98, "Nrpn Param LSB" },
    { 99, "Nrpn Param MSB" },
    { 100, "Exppedal" },
    { 101, "RPN Param MSB" },
    { 102, "ENV5 Attack" },
    { 103, "ENV5 Decay" },
    { 104, "ENV5 Sustain" },
    { 105, "ENV5 Release" },
    { 106, "ARP Division" },
    { 107, "ARP Gate" },
    { 108, "ARP Mode" },
    { 109, "ARP Ratchet" },
    { 110, "ARP Chance" },
    { 111, "OSC1 Cent" },
    { 112, "OSC2 Cent" },
    { 113, "OSC3 Cent" },
    { 114, "OSC3 F Rate" },
    { 115, "Noise F Rate" },
    { 116, "Ring MOD F Rate" },
    { 117, "ST Width" },
    { 118, "OSC1 F Rate" },
    { 119, "OSC2 F Rate" },
    { 0, nullptr }
};

struct InstrumentCCs {
    const char* name;
    const CCLabel* ccArray;
};

const InstrumentCCs allInstruments[] = {
    { "None", nullptr },
    { "chase-bliss_mood-mkii_deluge", chase_bliss_mood_mkii_deluge },
    { "hydrasynth", hydrasynth },
    { "lost_found", lost_found },
    { "microfreak", microfreak },
    { "micromonsta-2", micromonsta_2 },
    { "mood_mk2", mood_mk2 },
    { "neutron", neutron },
    { "polyend_acd", polyend_acd },
    { "polyend_fat", polyend_fat },
    { "polyend_grain", polyend_grain },
    { "polyend_phz", polyend_phz },
    { "polyend_pmd", polyend_pmd },
    { "polyend_vap", polyend_vap },
    { "polyend_wavs", polyend_wavs },
    { "polyend_wtfm", polyend_wtfm },
    { "volca-beats", volca_beats },
    { "volca-fm", volca_fm },
    { "volca-keys", volca_keys },
    { nullptr, nullptr } // sentinel
};
